### Let’s talk about NumPy — for Data Science Beginners

In [151]:
#Numpy stands for numerical python 
#Numpy use of scientific array calculation
#Numpy is a module or library of python
#Array that create in numpy called numpy.ndarray datatype
#Numpy is fast over than list
#Array is a homogenous elements
#we can create 1d 2d 3d 4d and so on array through numpy
#we can arithmatic or tignometric operation on an array.


In [152]:
import numpy as np

In [153]:
#To create a array in numpy we use array function np.array()

In [154]:
#We can create array by the use of list

In [155]:
l = [11,12,13,14]

In [156]:
arr = np.array(l)

In [157]:
arr

array([11, 12, 13, 14])

In [158]:
#check dtype

In [159]:
type(arr)

numpy.ndarray

In [160]:
#check dimension of the array by the use ndim function
arr.ndim

1

In [161]:
arr

array([11, 12, 13, 14])

In [162]:
#check the shape of the array by the use of shape function
arr.shape

(4,)

In [163]:
#We can also create array by the use of arange function 
arr1 = np.array(np.arange(100))

In [164]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [165]:
#we can reshape our array by the use of np.reshape function
arr1.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
arr1.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [167]:
arr1.reshape(2,50)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [168]:
arr1.reshape(50,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [169]:
arr1.reshape(25,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [170]:
arr2 = arr1.reshape(2,2,25)

In [171]:
arr2.shape

(2, 2, 25)

In [172]:
arr2.ndim

3

In [173]:
arr2

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [174]:
arr4 =np.array([[[[12,11,13,14]]]])

In [175]:
arr4

array([[[[12, 11, 13, 14]]]])

In [176]:
arr5= np.array([[[10,11,12],[19,15,17],[23,24,25]],
               [[100,110,120],[190,150,170],[230,240,250]]])

In [177]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

In [178]:
arr5.ndim

3

In [179]:
arr5.shape

(2, 3, 3)

In [180]:
arr5[0]

array([[10, 11, 12],
       [19, 15, 17],
       [23, 24, 25]])

In [181]:
arr5[0][0]

array([10, 11, 12])

In [182]:
arr4.ndim

4

## Array Indexing

In [183]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

In [184]:
arr5[0]

array([[10, 11, 12],
       [19, 15, 17],
       [23, 24, 25]])

In [185]:
arr5[1]

array([[100, 110, 120],
       [190, 150, 170],
       [230, 240, 250]])

In [186]:
arr5[1][0]

array([100, 110, 120])

In [187]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

In [188]:
arr5[1][0][0]

100

In [189]:
arr5[1][0]

array([100, 110, 120])

In [190]:
arr5[1][1]

array([190, 150, 170])

In [191]:
arr5[1][2]

array([230, 240, 250])

## Advance Indexing

In [192]:
arr = np.array([[12,13,17,18],[10,11,12,14]])

In [193]:
arr

array([[12, 13, 17, 18],
       [10, 11, 12, 14]])

In [198]:
row = np.array([[0,1],[1,1]])
col = np.array([[0,0],[0,1]])

In [199]:
arr[row,col]

array([[12, 10],
       [10, 11]])

In [200]:
row = np.array([[0,0],[1,1]])
col = np.array([[0,3],[0,3]])

In [201]:
arr[row,col]

array([[12, 18],
       [10, 14]])

In [202]:
###############################Indexing End#########################################

In [203]:
#we can create zero matrix by the use of np.zeros function

In [204]:
z_matrix = np.zeros(10)

In [205]:
z_matrix

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [206]:
#we can create one matrix by the use of np.ones function

In [207]:
ones_matrix = np.ones(10)

In [208]:
ones_matrix

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [209]:
#we can create identical matrix by the use of eye function
eye_matrix = np.eye(10)

In [210]:
eye_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [211]:
#we can give datatype in the arry function

In [212]:
d_arr = np.array([12,13,14],dtype=float)

In [213]:
d_arr

array([12., 13., 14.])

In [214]:
#we can also give complex data type
d_arr = np.array([12,13,14],dtype=complex)

In [215]:
d_arr

array([12.+0.j, 13.+0.j, 14.+0.j])

In [216]:
#we can also give string data type
d_arr = np.array([12,13,14],dtype=str)

In [217]:
d_arr

array(['12', '13', '14'], dtype='<U2')

In [218]:
# we can also make zero matrix with dtype int
z_matrix = np.zeros(10,dtype=int)

In [219]:
z_matrix

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [220]:
# we can also make ones matrix with dtype int
z_matrix = np.ones(10,dtype=int)

In [221]:
z_matrix

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [222]:
#we can also create our array by the use linspace function


In [223]:
lin_arr = np.array(np.linspace(1,2,10))

In [224]:
lin_arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [225]:
#We can create the matrix by the random number

In [226]:
rand_matrix = np.random.rand(4,3)

In [227]:
rand_matrix

array([[0.81085782, 0.40398074, 0.51954757],
       [0.44542047, 0.42370615, 0.76181299],
       [0.31980493, 0.85362582, 0.24155495],
       [0.10792354, 0.3588793 , 0.36646568]])

In [228]:
type(rand_matrix)

numpy.ndarray

### Using random.rand(), we can generate an array of random numbers of the shape we pass to it from uniform distribution over 0 to 1.

### And if we want a two-dimensional array of 5rows and 4columns:

In [229]:
myrand = np.random.rand(5,4)

In [230]:
myrand

array([[0.200794  , 0.31728706, 0.47921483, 0.60663477],
       [0.32878755, 0.79364901, 0.5491954 , 0.33487815],
       [0.77109328, 0.43788093, 0.56904605, 0.2996039 ],
       [0.06085258, 0.09936976, 0.63624027, 0.32658453],
       [0.24687409, 0.64312515, 0.92475832, 0.34947885]])

### Using randn(), we can generate random samples from Standard, normal or Gaussian distribution centered around 0. For example, let’s generate 7 random numbers:

In [231]:
ndis = np.random.randn(10)

In [232]:
ndis

array([-0.32648095,  1.61407382, -1.54529456,  1.72662166, -1.50312843,
        0.51536024,  0.30154742,  1.20126732, -0.50633444,  0.77338463])

In [233]:
i = 0
while(i<=10):
    rand_int = np.random.randint(10)
    print(rand_int)
    i = i+1

9
3
6
3
9
7
2
5
7
7
2


In [234]:
#arithmatic operation in array

In [235]:
a = np.array([10,11,12])
b = np.array([20,25,87])

In [236]:
a+b

array([30, 36, 99])

In [237]:
a*b

array([ 200,  275, 1044])

In [238]:
a/b

array([0.5       , 0.44      , 0.13793103])

In [239]:
a%b

array([10, 11, 12], dtype=int32)

In [240]:
a**b

array([ 1661992960, -1995658389,           0], dtype=int32)

In [241]:
c = np.array([12,2])

In [242]:
sc_ar = np.array([2])

In [243]:
a

array([10, 11, 12])

In [244]:
sc_ar

array([2])

In [245]:
a*sc_ar

array([20, 22, 24])

In [246]:
a+sc_ar

array([12, 13, 14])

In [247]:
a**sc_ar

array([100, 121, 144], dtype=int32)

In [248]:
a/sc_ar

array([5. , 5.5, 6. ])

## Numpy 24-02-2021 

In [249]:
a = np.random.randint(0,10,20)

In [250]:
a

array([1, 3, 5, 9, 7, 2, 9, 3, 2, 9, 4, 9, 5, 2, 5, 3, 2, 8, 9, 3])

In [251]:
a.max()

9

In [252]:
a.min()

1

In [253]:
a.ptp()

8

In [254]:
arr = np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])

In [255]:
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [256]:
np.percentile(arr,100)

21.0

There is two types of Descriptive analysis of our data 
1.Measure of central tendacy 
In which we look at the data in the central point from 
1.1 Mean
1.2.Median
1.3.Mod
2.Mesure of despressio of the data 
In which we check how spread our data is 
2.1 Range
2.2 Variance
2.3 Standard devaiation
2.4 I.Q.R (Inter quartile range)




In [257]:
#we can calculate the mean by the mean fucntion
np.mean(arr)

15.5

In [258]:
a = np.array([10,11,12,13,10,10,13,13,13])

In [259]:
s.mode(a)

NameError: name 's' is not defined

In [126]:
arr = np.array([[5,2,2],[2,3,4],[3,3,2]])

In [127]:
arr.ndim

2

In [128]:
arr

array([[5, 2, 2],
       [2, 3, 4],
       [3, 3, 2]])

In [ ]:
#Thre is different mode in different libraries

In [134]:
s.mode?

Object `s.mode` not found.


In [279]:
from scipy.stats import mode 

In [286]:
x_mode, counts = mode([[1, 1, 2],
                       [3, 3, 3],
                       [1, 3, 2],
                       [1, 3, 2]], axis=0)

In [287]:
x_mode

array([[1, 3, 2]])

In [288]:
counts

array([[3, 3, 3]])

In [139]:
arr

array([[5, 2, 2],
       [2, 3, 4],
       [3, 3, 2]])

In [140]:
arr = np.array([[2,3,2],[4,3,4],[0,3,0]])

In [141]:
arr

array([[2, 3, 2],
       [4, 3, 4],
       [0, 3, 0]])

In [142]:
x_mode, counts = mode(arr,axis=0)

In [143]:
x_mode

array([[0, 3, 0]])

In [144]:
counts

array([[1, 3, 1]])

In [145]:
np.array([12,13,14])

array([12, 13, 14])

#Brodcastin in numpy

## The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

#### If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

Broadcasting is possible if the following rules are satisfied −

Array with smaller ndim than the other is prepended with '1' in its shape.

Size in each dimension of the output shape is maximum of the input sizes in that dimension.

An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true −

Arrays have exactly the same shape.

Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.

Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [146]:
ba = np.array([[12,13,141,15],[121,131,142,150],[120,135,143,12],[18,15,14,15]])

In [147]:
ba

array([[ 12,  13, 141,  15],
       [121, 131, 142, 150],
       [120, 135, 143,  12],
       [ 18,  15,  14,  15]])

In [264]:
ba1 = np.array([2,3,4,2])

In [265]:
ba*ba1

array([[ 24,  39, 564,  30],
       [242, 393, 568, 300],
       [240, 405, 572,  24],
       [ 36,  45,  56,  30]])

## Loop iteration in numpy array

In [266]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

In [269]:
for val in arr5:
    print(type(val))
    print(val)

<class 'numpy.ndarray'>
[[10 11 12]
 [19 15 17]
 [23 24 25]]
<class 'numpy.ndarray'>
[[100 110 120]
 [190 150 170]
 [230 240 250]]


In [270]:
for val in arr5:
    if val>15:
        print(val)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [271]:
for val in np.nditer(arr5):
    print(val)

10
11
12
19
15
17
23
24
25
100
110
120
190
150
170
230
240
250


In [272]:
for val in np.nditer(arr5):
    if val>15:
        print(val)

19
17
23
24
25
100
110
120
190
150
170
230
240
250


In [273]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

### NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [274]:
sumi = 0
for val in np.nditer(arr5):
    sumi = sumi+val
print(sumi)

1716


In [275]:
arr5

array([[[ 10,  11,  12],
        [ 19,  15,  17],
        [ 23,  24,  25]],

       [[100, 110, 120],
        [190, 150, 170],
        [230, 240, 250]]])

In [276]:
arr5.mean()

95.33333333333333

AttributeError: 'numpy.ndarray' object has no attribute 'median'