In [3]:
#NUmpy is module (library) in python for the work of scientific array manipulation
#Numpy stands for numerical python 
#we can create 1d 2d 3d 4d and so on array on it
#We can easilty perform airthmetic and tignometric operation on that array
#it is numpy.ndarray data dtype


In [2]:
#how to import a module?
import numpy as np

In [4]:
a = np.array([12,13,14,15])

In [5]:
type(a)

numpy.ndarray

In [14]:
a

array([12, 13, 14, 15])

In [15]:
a.ndim

1

In [16]:
arr = np.array([[10,11,12,13],[11,14,18,19]])

In [17]:
arr

array([[10, 11, 12, 13],
       [11, 14, 18, 19]])

In [18]:
#ndim fucntion return dimension of the array
arr.ndim

2

In [19]:
#shape function return the shape of the array
arr.shape

(2, 4)

In [20]:
l = [100,110,112]

In [21]:
arr3 = np.array(l)

In [22]:
arr3

array([100, 110, 112])

In [23]:
arr4  = np.array(np.arange(10))

In [24]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr4.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
arr4.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
arr4.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [30]:
#difference b/w the list and array

In [31]:
l = [11,12,13,14]

In [32]:
l1 = [10,111,112,113]

In [33]:
l+l1

[11, 12, 13, 14, 10, 111, 112, 113]

In [34]:
#is list we can't do airthmatic operation when we do + it concatinate the list not perform arithmatic
#list is haterogenous but numpy array is homogenous objects
#list is slow as compare to array


In [43]:
a = np.array(np.arange(5))
b = np.array(np.arange(10,15))

In [44]:
a

array([0, 1, 2, 3, 4])

In [45]:
b

array([10, 11, 12, 13, 14])

In [46]:
a+b

array([10, 12, 14, 16, 18])

In [47]:
a*b

array([ 0, 11, 24, 39, 56])

In [48]:
a/b

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [49]:
a**b

array([        0,         1,      4096,   1594323, 268435456], dtype=int32)

In [50]:
a%b

array([0, 1, 2, 3, 4], dtype=int32)

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
b

array([10, 11, 12, 13, 14])

In [55]:
b-a

array([10, 10, 10, 10, 10])

In [56]:
arr5 = np.array(np.arange(25))

In [57]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ar = np.array(2)

In [59]:
ar

array(2)

In [60]:
arr5*ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [61]:
ar+arr5

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26])

In [62]:
ar/arr5

<ipython-input-62-b111f47b5e61>:1: RuntimeWarning: divide by zero encountered in true_divide
  ar/arr5


array([       inf, 2.        , 1.        , 0.66666667, 0.5       ,
       0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222,
       0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714,
       0.13333333, 0.125     , 0.11764706, 0.11111111, 0.10526316,
       0.1       , 0.0952381 , 0.09090909, 0.08695652, 0.08333333])

In [64]:
nwar = np.array(np.arange(30),dtype=np.int64)

In [65]:
nwar.dtype

dtype('int64')

In [66]:
nwar = np.array(np.arange(30),dtype=float)

In [67]:
nwar

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [68]:
np.array?

In [69]:
nwar1 = np.array(np.arange(30),dtype=complex)

In [70]:
nwar1

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j, 20.+0.j,
       21.+0.j, 22.+0.j, 23.+0.j, 24.+0.j, 25.+0.j, 26.+0.j, 27.+0.j,
       28.+0.j, 29.+0.j])

In [71]:
nwar1 = np.array(np.arange(30),dtype=str)

In [72]:
nwar1

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29'], dtype='<U11')

In [73]:
#array is homogenous type

hmar = np.array([10,11,12,'h'])

In [74]:
hmar

array(['10', '11', '12', 'h'], dtype='<U11')

In [75]:
m = np.array([2])

In [80]:
#np.empty create empty matrix the valu has come it garbage value
em_matrix = np.empty(5)

In [81]:
em_matrix

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [82]:
#np.zeroes create zero element matrix

In [84]:
zero_matr = np.zeros(10)

In [85]:
zero_matr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
zero_matr.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
#np.ones create matrix of 1 
matrix_of_one = np.ones(10)

In [88]:
matrix_of_one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
np.ones?

In [90]:
class Polygon:
    def __init__(self, no_of_sides):
        self.n = no_of_sides
        self.sides = [0 for i in range(no_of_sides)]

    def inputSides(self):
        self.sides = [float(input("Enter side "+str(i+1)+" : ")) for i in range(self.n)]

    def dispSides(self):
        for i in range(self.n):
            print("Side",i+1,"is",self.sides[i])

In [91]:
class Triangle(Polygon):
    def __init__(self):
        Polygon.__init__(self,3)

    def findArea(self):
        a, b, c = self.sides
        # calculate the semi-perimeter
        s = (a + b + c) / 2
        area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
        print('The area of the triangle is %0.2f' %area)

In [92]:
obj = Triangle(3)

TypeError: __init__() takes 1 positional argument but 2 were given

In [97]:
class Matz():
    def addi(a,b):
        return a+b
    

In [98]:
class Tigno(Matz):
    pass

In [99]:
obj = Tigno

In [100]:
obj.addi(12,12)

24