In [2]:
import numpy as np

In [3]:
a = np.array([[11,12,13,14],[100,110,120,130]])

In [4]:
a

array([[ 11,  12,  13,  14],
       [100, 110, 120, 130]])

In [5]:
a.ndim

2

In [6]:
row = np.array([[0,1],[0,1]])
col = np.array([[1,1],[0,1]])

In [7]:
na = a[row,col]

In [8]:
na

array([[ 12, 110],
       [ 11, 110]])

In [34]:
a = np.array([10,11,12,13,14])
b = np.array([10])

In [35]:
a*b

array([100, 110, 120, 130, 140])

In [40]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

In [41]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [42]:
a*b

array([[ 0.,  0.,  0.],
       [10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [43]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([5])

In [44]:
a+b

array([[ 5.,  5.,  5.],
       [15., 15., 15.],
       [25., 25., 25.],
       [35., 35., 35.]])

In [45]:
a*b

array([[  0.,   0.,   0.],
       [ 50.,  50.,  50.],
       [100., 100., 100.],
       [150., 150., 150.]])